codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      logic:  # declare a new status context "logic"
        target: 85
        threshold: 5
        base: auto
        if_not_found: success
        if_ci_failed: success
        informational: false # fail checks if not up to standards
        only_pulls: false
    patch: false
    changes: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true

ignore:
  - '**/*.kts'
  - '**/*.xml'
  - '**/*.gradle'

  # Tests that probably use Robolectric
  - '*-ui/**'
  - '**/ui/**'
  - '**/widget/**'
  - '**/*Activity.*'
  - '**/*Fragment.*'
