name: Dependencies

on:
  schedule:
    - cron: '0 0 * * 1,3,5'

jobs:
  updates:
    name: Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Copy CI properties
        run: |
          mkdir -p ~/.gradle
          cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Check for dependency updates
        run: ./gradlew dependencyUpdates

      - name: Upload dependency updates report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: dependency-updates
          path: build/dependencyUpdates
