name: Greeting

on: [pull_request, issues]

jobs:
  greeting:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Hello! Good job creating your first issue! It''s people like you who make the world better.'
          pr-message: 'Hello! Good job creating your first pull request! It''s people like you who make the world better.'
